
# PostgreSQL development database setup. This configuration presumes that you 
# have a database user set up with the same name as your login, and it doesn't
# require a password.

development:
  adapter: postgresql
  database: karma_development

test:
  adapter: postgresql
  database: karma_test
